### ISSUE TITLE
Change MuxSelect Labels on main screen 

### ISSUE THREAD

**Issue by cristinasewell** [cristinasewell/ATCM_PyDM_Screens#89]
**UP Converter**

- 0: Disabled
- 1: Test
- 2: RF IN 2: ADC0 (FP)
- 3: RF IN 1: ADC1 (FP)
- 4: RF IN 3: ADC2 (FP)
- 5: RF OUT MON: ADC3 (FP)
- 6: TRIG MON: ADC4 (FP)
- 7: DC IN 1: ADC5 (FP) 
- 8: ADC6
- 9: RF OUT: DAC0 (FP)
- ....

**Down Converter**

- 0: Disabled
- 1: Test
- 2: RF IN 2: ADC0 (FP)
- 3: RF IN 1: ADC1 (FP)
- 4: RF IN 4: ADC2 (FP)
- 5: RF IN 3: ADC3 (FP)
- 6: RF IN 6: ADC4 (FP)
- 7: RF IN 5: ADC5 (FP) 
- 8: ADC6
- 9: LO PLL DAC: DAC0 
- 10: CLK PLL DAC: DAC1 
- 11: DAC OUT: DAC2 (FP)

**Comment by cristinasewell** [comment]
@jesusvasquez333 for the `LO PLL DAC` and `CLK PLL DAC` - on the `Up Converter` are they FP - or internal connections?

**Comment by jesusvasquez333** [comment]
Those PLLs are internal connections
